import scrapy


class MangItem(scrapy.Item):

    title = scrapy.Field()
    authors = scrapy.Field()
    num_vol = scrapy.Field()
    num_chap = scrapy.Field()
    #start_year = scrapy.Field()
    #end_date = scrapy.Field()
    status = scrapy.Field()
    mal_score = scrapy.Field()
    mal_ranking = scrapy.Field()
    mal_popularity = scrapy.Field()
    mal_url = scrapy.Field()
    synopsis = scrapy.Field()
    genres = scrapy.Field()
    Action = scrapy.Field()
    Adventure= scrapy.Field()
    Cars= scrapy.Field()
    Comedy= scrapy.Field()
    Dementia= scrapy.Field()
    Demons= scrapy.Field()
    Doujinshi= scrapy.Field()
    Drama= scrapy.Field()
    Ecchi= scrapy.Field()
    Fantasy= scrapy.Field()
    Game= scrapy.Field()
    GenderBender= scrapy.Field()
    Harem= scrapy.Field()
    Hentai= scrapy.Field()
    Historical= scrapy.Field()
    Horror= scrapy.Field()
    Josei= scrapy.Field()
    Kids= scrapy.Field()
    Magic= scrapy.Field()
    MartialArts= scrapy.Field()
    Mecha= scrapy.Field()
    Military= scrapy.Field()
    Music= scrapy.Field()
    Mystery= scrapy.Field()
    Parody= scrapy.Field()
    Police= scrapy.Field()
    Psychological= scrapy.Field()
    Romance= scrapy.Field()
    Samurai= scrapy.Field()
    School= scrapy.Field()
    SciFi= scrapy.Field()
    Seinen= scrapy.Field()
    Shoujo= scrapy.Field()
    ShoujoAi= scrapy.Field()
    Shounen= scrapy.Field()
    ShounenAi= scrapy.Field()
    SliceofLife= scrapy.Field()
    Space= scrapy.Field()
    Sports= scrapy.Field()
    SuperPower= scrapy.Field()
    Supernatural= scrapy.Field()
    Thriller= scrapy.Field()
    Vampire= scrapy.Field()
    Yaoi= scrapy.Field()
    Yuri= scrapy.Field()
    #mc = scrapy.Field()
    #mc_gender = scrapy.Field()
    #harem = scrapy.Field()
    #harem_genders = scrapy.Field()
    #selected_partner = scrapy.Field()


class BakaItem(scrapy.Item):
    title = scrapy.Field()
    num_vol = scrapy.Field()
    status = scrapy.Field()
    baka_url = scrapy.Field()
    synopsis = scrapy.Field()
    genres = scrapy.Field()

    Action = scrapy.Field()
    Adult = scrapy.Field()
    Adventure = scrapy.Field()
    Comedy = scrapy.Field()
    Doujinshi = scrapy.Field()
    Drama = scrapy.Field()
    Ecchi = scrapy.Field()
    Fantasy = scrapy.Field()
    GenderBender = scrapy.Field()
    Harem = scrapy.Field()
    Hentai = scrapy.Field()
    Historical = scrapy.Field()
    Horror = scrapy.Field()
    Josei = scrapy.Field()
    Lolicon = scrapy.Field()
    MartialArts = scrapy.Field()
    Mature = scrapy.Field()
    Mecha = scrapy.Field()
    Mystery = scrapy.Field()
    Psychological = scrapy.Field()
    Romance = scrapy.Field()
    SchoolLife = scrapy.Field()
    Scifi = scrapy.Field()
    Seinen = scrapy.Field()
    Shotacon = scrapy.Field()
    Shoujo = scrapy.Field()
    ShoujoAi = scrapy.Field()
    Shounen = scrapy.Field()
    ShounenAi = scrapy.Field()
    SliceofLife = scrapy.Field()
    Smut = scrapy.Field()
    Sports = scrapy.Field()
    Supernatural = scrapy.Field()
    Tragedy = scrapy.Field()
    Yaoi = scrapy.Field()
    Yuri = scrapy.Field()

class CharItem(scrapy.Item):
    title = scrapy.Field()

    #mc_gender = scrapy.Field()
    #harem = scrapy.Field()
    #harem_genders = scrapy.Field()
    #selected_partner = scrapy.Field()











